### ISSUE TITLE
Week 2 Reference Files : Box

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team1#1]
- Overview of Hills
- Week 2 Assignments
[]https://app.box.com/s/0d56tulvikzilbzixgfc1fg2h3c963yn

**Comment by akallish** [comment]
@akallish I do not understand what to do. Can you weigh in on this?

**Comment by akallish** [comment]
@JSpragueDesign @sliu131 @zixuan-zhaozhao  please move this task to the product backlog pipeline and when ready to initiate the task, please move it to the in progress pipeline. Remember that all asynchronous task conversations need to happen in the GitHub tasks found in the issues tab. To reference people, use their GitHub handle. If you need help reference @akallish and I will get a notification. Thanks.

**Comment by akallish** [comment]
@JSpragueDesign @sliu131 @zixuan-zhaozhao please move this task to the product backlog pipeline and when ready to initiate the task, please move it to the in progress pipeline. Remember that all asynchronous task conversations need to happen in the GitHub tasks found in the issues tab. To reference people, use their GitHub handle. If you need help reference @akallish and I will get a notification. Thanks.

**Comment by JSpragueDesign** [comment]
Jeff is done with reviewing the pdf

**Comment by sliu131** [comment]
Sike is done reviewing the content.

**Comment by zixuan-zhaozhao** [comment]
Zixuan has down with reviewing the PDF.

**Comment by kanalchhajed** [comment]
Kanal is done reviewing as well
