### ISSUE TITLE
Week 03 : In Mural : Sub-Hills to epics to stories

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team1#10]
You can group related sub-hills together into an epic, or a body of work. An epic has an overarching name. Usually epics are associated with sprints as the related stories are worked on to create a unified deliverable. 

Use the mural template to do this : (http://bit.ly/2YsQ46J)

**Comment by JSpragueDesign** [comment]
### Live plan during planning meeting:
Synced: **Sunday at 3** - Sub-Hill Clarity, Define Epics, Write small number of Stories, Create Github entry template

ASynced: Build out Stories **(20 total)**

Synced, if needed: Review stories
