### ISSUE TITLE
Week 03 : In GitHub : Transfer stories to GitHub

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team1#11]
- create two new tags : “story” and specific “(epic name)” tags
- create a new issues and give a story a name assign the team to the story
- select appropriate tags for story choose week three milestone state what part of the hill and what part of the sub-hill it is decomposed from
- draft the first iteration of the hill statement other team members then iterate and then @ reference others on the team  just like the hills/definitions/sub hills exercise, it is important to refine the language of the story

**Comment by JSpragueDesign** [comment]
### Live Planning Meeting:

Build out structure during the synced meeting at 3p Sunday

**Comment by JSpragueDesign** [comment]
Who will transfer what:
Epic 1 - split, noted in Mural
Epic 2 - @sliu131 
Epic 3 - @JSpragueDesign 
Epic 4 - @zixuan-zhaozhao 
Epic 5 - @kanalchhajed

**Comment by JSpragueDesign** [comment]
Epic 3 (& assigned parts of E1) has been transferred to GitHub. Please take a look and comment refinements!

**PS** To copy the formatting from our templates, you need to edit the Issue we created and copy the text from there (if you don't see special characters eg *,**,> , the formatting won't copy over)

**Comment by zixuan-zhaozhao** [comment]
Epic 4 and assigned part of Epic 1 have been transferred to GitHub. 
Please take a look and comment if you have time Thx!

**Comment by kanalchhajed** [comment]
Epic 5 and the assigned stories of Epic 1 are transferred to GitHub and moved to the product backlog in Zenhub. 
Review and comment to refine the stories! @sliu131 @JSpragueDesign @zixuan-zhaozhao
