### ISSUE TITLE
Week 2 Homework : Mural

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team1#3]
[]http://bit.ly/39E4C94
- Who are we as a team Mural
- Complete goals, hills, definitions & sub-hills (Example of hill definition : []http://bit.ly/2BSgO6p

**Comment by akallish** [comment]
@JSpragueDesign @sliu131 @zixuan-zhaozhao please move this task to the product backlog pipeline and when ready to initiate the task, please move it to the in progress pipeline. Remember that all asynchronous task conversations need to happen in the GitHub tasks found in the issues tab. To reference people, use their GitHub handle. If you need help reference @akallish and I will get a notification. Thanks.

**Comment by akallish** [comment]
I am glad you moved these tasks to in progress.

**Comment by akallish** [comment]
![Screen Shot 2021-01-23 at 1 49 53 PM](https://user-images.githubusercontent.com/35602533/105612615-04596b00-5d83-11eb-8d45-8057a474eaef.jpg)

@JSpragueDesign @sliu131 @zixuan-zhaozhao  This updated description should help you with the Mural on the hills

**Comment by JSpragueDesign** [comment]
@kanalchhajed , Test Notification

**Comment by JSpragueDesign** [comment]
@kanalchhajed @sliu131 @zixuan-zhaozhao 
I filled in my interpretation of the Hills we discussed in the Mural. version Zero.

The who's I used are "Individuals clinicians to learn", "Teams to collaborate", and "Admins to track and manage".... essentially

The other direction we could go is; Mentee, Mentor, Admin.

Let me know you're thoughts... I figured I'd take a pass at it.

**Comment by akallish** [comment]
> I filled in my interpretation of the Hills we discussed in the Mural. version Zero.

@JSpragueDesign thanks for taking the first pass at populating the Mural. That will help the rest of the team add or modify your content. It is very important that @sliu131 who is the product manager of this project help guide the team in understanding the intent and desired outcomes of this AbilityLab LMS concept. IT IS VERY IMPORTANT for the team to meet synchronously to collaborate on the mural to get aligned on the hills, choose a hill and get the definitions of one hill done. Then a session on generating sub-hill statements.

**Comment by sliu131** [comment]
I added some details on the board in orange sticky notes. Please feel free to leave questions.

**Comment by akallish** [comment]
@sliu131 @JSpragueDesign @kanalchhajed @zixuan-zhaozhao I reviewed your hills mural and liked what I read. The goal seems too rigid and does not really describe the value that @sliu131 project outlined (to me). Here is a revised goal which needs to be refined :

"Slab is a tailored integrative learning platform that caters to the learning styles of inexperienced clinicians which combines tacit and explicit knowledge into a deeper learning cycle with mentors & administrators in order to deliver better AbilityLab patient care."

Keep iterating.

**Comment by kanalchhajed** [comment]
@JSpragueDesign @sliu131 @zixuan-zhaozhao . Thanks, @JSpragueDesign for drafting the hill statements. Added a few comments that we could discuss during our meeting. We might need to have a discussion on what is "wow" worthy or how tactical it should get. @sliu131 thanks for posting the notes, were really helpful but feel like I need some more of your insight for the administrator part. Thanks and discuss soon! @akallish we will keep working on our goal.

**Comment by akallish** [comment]
> We might need to have a discussion on what is "wow" worthy or how tactical it should get.

@kanalchhajed the wow should be the ultimate expression and benefit of doing the what for the who.

**Comment by akallish** [comment]
@sliu131 @JSpragueDesign @kanalchhajed @zixuan-zhaozhao 

Good Morning! I reviewed your hills mural and it is shaping up nicely.

- the goal is better, but slightly long. It is OK for now
- hills are clear
- definitions seem clear
- in the sub-hills, it is curious you have none that connect to the administrator

**Comment by akallish** [comment]
@sliu131 @JSpragueDesign @kanalchhajed @zixuan-zhaozhao Good Morning. I was thinking about the SLab goal statement and think it is too long and complicated. Below is an iteration to consider :

"S Lab is a tailored integrative learning, planning, and collaboration platform that  fosters deeper learning experiences for inexperienced clinicians, and collaboration with experienced colleagues connecting their explicit and tacit knowledge for deeper learning experiences in order to deliver better AbilityLab Patient care."

**Comment by akallish** [comment]
@sliu131 @JSpragueDesign @kanalchhajed @zixuan-zhaozhao I reviewed your sub-hills and listed four questions based on Hill 1 and my knowledge of the chosen project. They are on black post-its.
