### ISSUE TITLE
Week 03 : Review Presentations

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team1#7]
Re-Review these FIRST
• Overview
• To Do

[Link to Box](https://app.box.com/s/nmxlf3h37xgurza8rlqv6au0et0da0e7)

**Comment by JSpragueDesign** [comment]
> User stories are often written on index cards or sticky notes, stored in a shoe box, and arranged on walls or tables to facilitate planning and discussion. As such, they strongly shift the focus from writing about features to discussing them. In fact, these discussions are more important than whatever text is written.

From [This article](https://www.mountaingoatsoftware.com/agile/user-stories)

Reminds me of a qual research debrief when you share the details, create notes and artifacts (diagrams, sketches, etc) and have critical discussions about what everything means. The artifacts start to become the physical (or digital) embodiment of the shared understanding of a situation. Taken out of the context of the discussion, their meaning can change.

**Comment by akallish** [comment]
@JSpragueDesign thanks for adding the information. Stories have a precision about them and the context of their meaning will not change as they trace to an epic, Si hill, hill then goal.

**Comment by JSpragueDesign** [comment]
@akallish Right, I found it interesting how multiple articles stressed the importance of the conversation around stories; promoting a shared understanding on all levels of the team. I believe it's part of the no hidden work, and mapping actions, as you said, back to the goal.

**Comment by akallish** [comment]
> @akallish Right, I found it interesting how multiple articles stressed the importance of the conversation around stories; promoting a shared understanding on all levels of the team. I believe it's part of the no hidden work, and mapping actions, as you said, back to the goal.

Exactly.

**Comment by JSpragueDesign** [comment]
Jeff - Done

**Comment by kanalchhajed** [comment]
Kanal - Done

**Comment by sliu131** [comment]
Sike - Done

**Comment by zixuan-zhaozhao** [comment]
Zixuan - Done
