### ISSUE TITLE
Week 03 : Review Online Written Content

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team1#8]
Please read these articles in their entirety - before doing the tasks

What are user stories? 
(http://bit.ly/2Gmw7Y6 )
(http://bit.ly/2IQVdwl )
(http://bit.ly/2pDhEgx)

GitHub Issues 
(http://bit.ly/2rjMACX)

Creating tasks in issues
( http://bit.ly/2HSHGGG)

Text Formatting 
(http://bit.ly/2YceDov)

**Comment by kanalchhajed** [comment]
> _If you don’t know who the users and customers are and why they would want to use the product, then you should not write any user stories. Carry out the necessary user research first, for example, by observing and interviewing users. Otherwise, you take the risk of writing speculative stories that are based on beliefs and ideas—but not on data and empirical evidence.

Read more at: https://www.romanpichler.com/blog/10-tips-writing-good-user-stories/
Copyright © Pichler Consulting_

The above makes me wonder how everyone on the team (designers, researchers, developers, business folks) can write user stories if you need to deeply understand the users and the product. Since not everyone is involved in the research it can lead to personal biases creeping up.

**Comment by kanalchhajed** [comment]
Oh I think the collaboration and discussion answers my earlier comment

**Comment by JSpragueDesign** [comment]
Nice find @kanalchhajed , I agree that its through discussion and collaboration that all team members grow their understanding of who and why. If someone is just focused on the what, they are likely to build the thing in an non user centered way.

Everything traces back to the goal... we should iterate ours again at our meeting tomorrow haha. (is laughing allowed in GitHub?)

**Comment by JSpragueDesign** [comment]
Jeff - Done

**Comment by kanalchhajed** [comment]
@JSpragueDesign Agree, also aligns with what you commented on earlier! True, we should work on the goal, maybe we add that to our plan/agenda. (GitHub does give me the lol vibe instead of the hahaha, lol :p)

**Comment by kanalchhajed** [comment]
Done!

**Comment by sliu131** [comment]
Sike - Done, yeah I see it as a facilitation tool rather than implementation requirements

**Comment by zixuan-zhaozhao** [comment]
Done
