### ISSUE TITLE
Week 03 : Review Videos

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team1#9]
Please watch these videos in their entirety - before doing the tasks 

GitHub Overviews 
(http://bit.ly/2Gedxhz )
(http://bit.ly/2G8muwR)

GitHub & ZenHub 
(https://bit.ly/3qWfLZT)

How to write user stories
( http://bit.ly/2IMDQwJ )
(http://bit.ly/2I1gZMM)

**Comment by JSpragueDesign** [comment]
Jeff - Done.
The automatic gant chart/project burndown calculator/due date tracker built into ZenHub looks awesome! It really hints at the value of assigning points to everything

**Comment by akallish** [comment]
> Jeff - Done.
> The automatic gant chart/project burndown calculator/due date tracker built into ZenHub looks awesome! It really hints at the value of assigning points to everything

Which report are you viewing? Most of these track task velocity

**Comment by sliu131** [comment]
Sike - Done

**Comment by JSpragueDesign** [comment]
@akallish The Github & ZenHub Video. They call it a ZenHub Roadmap.
[At 8:30 in the video](https://youtu.be/dMG_-551xV4?t=509).

My description was way off. But I can imagine it's useful for a product manager.

**Comment by akallish** [comment]
@JSpragueDesign the roadmap is a Venmo diagram to show the different sprint items and their progress. Yes, product managers would definitely use this as a planning and tracking dashboard

**Comment by zixuan-zhaozhao** [comment]
Zixuan - Done
